# Задание 1


In [1]:
import numpy as np

In [2]:
a=np.array([[1,6],
            [2,8],
            [3,11],
            [3,10],
            [1,7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
a.shape

(5, 2)

In [7]:
mean_a=a.mean(axis=0)

In [8]:
mean_a

array([2. , 8.4])

# Задание 2

In [33]:
a_centered=a-mean_a

In [34]:
a_centered.shape[0]

5

In [51]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3

In [43]:
a_centered_sp=np.dot(a_centered[:,0],a_centered[:,1])

In [44]:
a_centered_sp

8.0

In [45]:
a_centered_cov=a_centered_sp/(a_centered.shape[0]-1)

In [46]:
a_centered_cov

2.0

# Задание 4

In [47]:
a_centered_cov=np.cov(a.T)

In [48]:
a_centered_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [49]:
a_centered_cov[0][1]

2.0